### ISSUE TITLE
AC02 problema con el deploy

### ISSUE THREAD

**Issue by MatiasBarraF** [IIC3103/2022-2-dudas#3]
Hola, al hacer el deploy con git push heroku master, o, git push heroku master:main me tira el error adjunto. Llevo un buen rato buscando en internet y no he podido dar con la solución. 
<img width="929" alt="terminal" src="https://user-images.githubusercontent.com/48270008/160149785-9165e610-db67-43e4-b935-d0d83ad20b80.png">

**Comment by dedarritchon** [comment]
Hola @MatiasBarraF!

Como se menciona en [esta respuesta](https://stackoverflow.com/questions/50026190/heroku-fails-to-install-pywin32-library),

la librería **pywin32** provee acceso a las APIs de Windows desde Python, el problema es que **Heroku no corre en máquinas con Windows** (corre en linux), por lo que derechamente **no se puede usar pywin32 en Heroku**. (No podrás usar esa dependencia en Heroku).

Trata de eliminar esa dependencia ya que lo más probable es que no la necesites para realizar la actividad.
Saludos!
